export const images={
    user_1:require('./images/user1/user1.png'),
    online:require('./images/indicator/online.png'),
    offline:require('./images/indicator/offline.png'),
    search: require('./images/icons/Pathsearchicon.png'),
    footsettings: require('./images/footericons/settings.png'),
    footpayment: require('./images/footericons/pay.png'),
    footchat: require('./images/footericons/chat.png'),
    footmenu: require('./images/footericons/menu.png'),
    footcommunity: require('./images/footericons/communities.png'),
    payicon:require('./images/paymentscreen/pay.png'),
    bankicon:require('./images/paymentscreen/bank.png'),
    addmoneyicon:require('./images/paymentscreen/add.png'),
    recharge:require('./images/paymentscreen/recharge.png'),
    flights:require('./images/paymentscreen/flights.png'),
    metro:require('./images/paymentscreen/metro.png'),
    movie:require('./images/paymentscreen/movie.png'),
    more:require('./images/paymentscreen/more.png'),
    shopping:require('./images/paymentscreen/shopping.png'),

}